#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path

from tools.project import (
    Object,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 3  # RSBE01_02
VERSIONS = [
    "RSBJ01_00",  # Japan Rev 0 (January 31, 2008)
    "RSBJ01_01",  # Japan Rev 1 (?)
    "RSBE01_01",  # USA Rev 1 (March 9, 2008)
    "RSBE01_02",  # USA Rev 2 (?)
    "RSBP01_00",  # PAL Rev 0 (June 27, 2008)
    "RSBP01_01",  # PAL Rev 1 (?)
    "RSBK01_00",  # Korea Rev 0 (April 29, 2010)
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-1"
config.compilers_tag = "20250812"
config.dtk_tag = "v1.7.5"
config.objdiff_tag = "v3.4.4"
config.sjiswrap_tag = "v1.2.2"
config.wibo_tag = "1.0.0"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    f"--defsym BUILD_VERSION={version_num}",
    f"--defsym VERSION_{config.version}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = None

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    # "-W all",
    "-O4,p",
    "-inline auto",
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-RTTI off",
    "-fp_contract on",
    "-str reuse",
    "-enc SJIS",
    "-i include",
    f"-i build/{config.version}/include",
    f"-DBUILD_VERSION={version_num}",
    f"-DVERSION_{config.version}",
]

cflags_common = [
    *cflags_base,
    "-DMATCHING",
    "-Iinclude",
    "-Iinclude/lib/PowerPC_EABI_Support/Runtime/Inc",
    "-Iinclude/lib/BrawlHeaders/Brawl/Include",
    "-Iinclude/lib/BrawlHeaders/nw4r/include",
    "-Iinclude/lib/BrawlHeaders/OpenRVL/include",
    "-Iinclude/lib/BrawlHeaders/OpenRVL/include/MetroTRK",
    "-Iinclude/lib/BrawlHeaders/OpenRVL/include/revolution",
    "-Iinclude/lib/BrawlHeaders/OpenRVL/include/RVLFaceLib",
    "-Iinclude/lib/BrawlHeaders/OpenRVL/include/stl",
    "-Iinclude/lib/BrawlHeaders/utils/include",
    "-RTTI on",
    "-ipa file",
]

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-use_lmw_stmw on",
    "-str reuse,pool,readonly",
    "-gccinc",
    "-common off",
    "-inline auto",
]

# REL flags
config.rel_strip_partial = True
cflags_rel = [
    *cflags_common,
    "-sdata 0",
    "-sdata2 0",
]

cflags_fighter = ["-O2,s" if flag == "-O4,p" else flag for flag in cflags_rel]
cflags_sora_enemy = ["-O2,s" if flag == "-O4,p" else flag for flag in cflags_rel]
cflags_st_starfox = [*cflags_rel, "-inline on,noauto"]

config.linker_version = "GC/3.0a5.2"

Matching = True  # Object matches and should be linked
NonMatching = False  # Object does not match and should not be linked
Equivalent = (
    config.non_matching
)  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.linker_version,
        "cflags": cflags_runtime,
        "host": False,
        "objects": [
            Object(NonMatching, "Runtime.PPCEABI.H/global_destructor_chain.c"),
            Object(NonMatching, "Runtime.PPCEABI.H/__init_cpp_exceptions.cpp"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/dispatch.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/udp_cc.c"),
            Object(Matching, "stub/fn_80406470.c"),
            Object(Matching, "stub/fn_803EF1C8.c"),
            Object(Matching, "stub/fn_803D8994.c"),
            Object(Matching, "stub/fn_803D66EC.c"),
            Object(Matching, "stub/fn_803A9A78.c"),
            Object(Matching, "stub/fn_803A9A70.c"),
            Object(Matching, "stub/fn_803930B8.c"),
            Object(Matching, "stub/fn_803900E4.c"),
            Object(Matching, "stub/fn_8038D4C8.c"),
            Object(Matching, "stub/fn_803899C4.c"),
            Object(Matching, "stub/fn_8038918C.c"),
            Object(Matching, "stub/fn_80389178.c"),
            Object(Matching, "stub/fn_803889B8.c"),
            Object(Matching, "stub/fn_803889A8.c"),
            Object(Matching, "stub/fn_80388968.c"),
            Object(Matching, "stub/fn_80388958.c"),
            Object(Matching, "stub/fn_80387DD0.c"),
            Object(Matching, "stub/fn_8037F1A4.c"),
            Object(Matching, "stub/fn_8037807C.c"),
            Object(Matching, "stub/fn_80374C10.c"),
            Object(Matching, "stub/fn_80374BE8.c"),
            Object(Matching, "stub/fn_80362F54.c"),
            Object(Matching, "stub/fn_8035A590.c"),
            Object(Matching, "stub/fn_80350C44.c"),
            Object(Matching, "stub/fn_80350C1C.c"),
            Object(Matching, "stub/fn_803328BC.c"),
            Object(Matching, "stub/fn_803318E4.c"),
            Object(Matching, "stub/fn_8032FCAC.c"),
            Object(Matching, "stub/fn_80318BD0.c"),
            Object(Matching, "stub/fn_80303004.c"),
            Object(Matching, "stub/fn_803028FC.c"),
            Object(Matching, "stub/fn_802F30CC.c"),
            Object(Matching, "stub/fn_802F28B4.c"),
            Object(Matching, "stub/fn_802E7870.c"),
            Object(Matching, "stub/fn_802E6F38.c"),
            Object(Matching, "stub/fn_802E46A8.c"),
            Object(Matching, "stub/fn_802DD500.c"),
            Object(Matching, "stub/fn_802DD4F8.c"),
            Object(Matching, "stub/fn_802DBC10.c"),
            Object(Matching, "stub/fn_802DBBC8.c"),
            Object(Matching, "stub/fn_802DBBB8.c"),
            Object(Matching, "stub/fn_802DBB04.c"),
            Object(Matching, "stub/fn_802DB9AC.c"),
            Object(Matching, "stub/fn_802DB97C.c"),
            Object(Matching, "stub/fn_802DB590.c"),
            Object(Matching, "stub/fn_802DB56C.c"),
            Object(Matching, "stub/fn_802DB55C.c"),
            Object(Matching, "stub/fn_802DAAF8.c"),
            Object(Matching, "stub/fn_802CEAA0.c"),
            Object(Matching, "stub/fn_802AA344.c"),
            Object(Matching, "stub/fn_802AA2FC.c"),
            Object(Matching, "stub/fn_802AA2C8.c"),
            Object(Matching, "stub/fn_802AA2B0.c"),
            Object(Matching, "stub/fn_802AA29C.c"),
            Object(Matching, "stub/fn_802A0BF0.c"),
            Object(Matching, "stub/fn_80298784.c"),
            Object(Matching, "stub/fn_8029875C.c"),
            Object(Matching, "stub/fn_80298744.c"),
            Object(Matching, "stub/fn_80298734.c"),
            Object(Matching, "stub/fn_80298258.c"),
            Object(Matching, "stub/fn_80298190.c"),
            Object(Matching, "stub/fn_80295130.c"),
            Object(Matching, "stub/fn_80295120.c"),
            Object(Matching, "stub/fn_80295108.c"),
            Object(Matching, "stub/fn_802947FC.c"),
            Object(Matching, "stub/fn_802915BC.c"),
            Object(Matching, "stub/fn_8028D8B4.c"),
            Object(Matching, "stub/fn_8028B66C.c"),
            Object(Matching, "stub/fn_8028AE34.c"),
            Object(Matching, "stub/fn_80289814.c"),
            Object(Matching, "stub/fn_8028980C.c"),
            Object(Matching, "stub/fn_8027CC14.c"),
            Object(Matching, "stub/fn_8027C904.c"),
            Object(Matching, "stub/fn_8027C8EC.c"),
            Object(Matching, "stub/fn_8027C83C.c"),
            Object(Matching, "stub/fn_8027C10C.c"),
            Object(Matching, "stub/fn_8027A194.c"),
            Object(Matching, "stub/fn_8027A0B0.c"),
            Object(Matching, "stub/fn_80279E10.c"),
            Object(Matching, "stub/fn_80279B9C.c"),
            Object(Matching, "stub/fn_802795A4.c"),
            Object(Matching, "stub/fn_802793CC.c"),
            Object(Matching, "stub/fn_8027919C.c"),
            Object(Matching, "stub/fn_802784A0.c"),
            Object(Matching, "stub/fn_802706B8.c"),
            Object(Matching, "stub/fn_802706B0.c"),
            Object(Matching, "stub/fn_8022F8E0.c"),
            Object(Matching, "stub/fn_80210EDC.c"),
            Object(Matching, "stub/fn_8020B898.c"),
            Object(Matching, "stub/fn_801F2E44.c"),
            Object(Matching, "stub/fn_801F2D34.c"),
            Object(Matching, "stub/fn_801F2C6C.c"),
            Object(Matching, "stub/fn_801EF010.c"),
            Object(Matching, "stub/fn_801D6E14.c"),
            Object(Matching, "stub/fn_801D6D80.c"),
            Object(Matching, "stub/fn_801D44D0.c"),
            Object(Matching, "stub/fn_801D3C38.c"),
            Object(Matching, "stub/fn_801D36BC.c"),
            Object(Matching, "stub/fn_801CF980.c"),
            Object(Matching, "stub/fn_801CF634.c"),
            Object(Matching, "stub/fn_801CF62C.c"),
            Object(Matching, "stub/fn_801CBD04.c"),
            Object(Matching, "stub/fn_801CAE40.c"),
            Object(Matching, "stub/fn_801C96A0.c"),
            Object(Matching, "stub/fn_801C6B8C.c"),
            Object(Matching, "stub/fn_801C4B00.c"),
            Object(Matching, "stub/fn_801C49A4.c"),
            Object(Matching, "stub/fn_801C38D8.c"),
            Object(Matching, "stub/fn_801C10E8.c"),
            Object(Matching, "stub/fn_801C1054.c"),
            Object(Matching, "stub/fn_801BF398.c"),
            Object(Matching, "stub/fn_801BF07C.c"),
            Object(Matching, "stub/fn_801BCBF4.c"),
            Object(Matching, "stub/fn_801B802C.c"),
            Object(Matching, "stub/fn_801B7EE0.c"),
            Object(Matching, "stub/fn_801B5DC0.c"),
            Object(Matching, "stub/fn_801B3FB4.c"),
            Object(Matching, "stub/fn_801AC5EC.c"),
            Object(Matching, "stub/fn_801A7550.c"),
            Object(Matching, "stub/fn_80189904.c"),
            Object(Matching, "stub/fn_80183618.c"),
            Object(Matching, "stub/fn_80179550.c"),
            Object(Matching, "stub/fn_801643C8.c"),
            Object(Matching, "stub/fn_8015D350.c"),
            Object(Matching, "stub/fn_8015D340.c"),
            Object(Matching, "stub/fn_8015A7C4.c"),
            Object(Matching, "stub/fn_8015A41C.c"),
            Object(Matching, "stub/fn_801542BC.c"),
            Object(Matching, "stub/fn_801542A8.c"),
            Object(Matching, "stub/fn_80154294.c"),
            Object(Matching, "stub/fn_80154278.c"),
            Object(Matching, "stub/fn_80153810.c"),
            Object(Matching, "stub/fn_8014E6B4.c"),
            Object(Matching, "stub/fn_8014CE60.c"),
            Object(Matching, "stub/fn_8014CB1C.c"),
            Object(Matching, "stub/fn_80149910.c"),
            Object(Matching, "stub/fn_80138730.c"),
            Object(Matching, "stub/fn_80138708.c"),
            Object(Matching, "stub/fn_801077D0.c"),
            Object(Matching, "stub/fn_80106A5C.c"),
            Object(Matching, "stub/fn_801048A4.c"),
            Object(Matching, "stub/fn_80104890.c"),
            Object(Matching, "stub/fn_80101370.c"),
            Object(Matching, "stub/fn_800FF2BC.c"),
            Object(Matching, "stub/fn_800FD648.c"),
            Object(Matching, "stub/fn_800FBDEC.c"),
            Object(Matching, "stub/fn_800F1750.c"),
            Object(Matching, "stub/fn_800F01B8.c"),
            Object(Matching, "stub/fn_800F00A4.c"),
            Object(Matching, "stub/fn_800CB824.c"),
            Object(Matching, "stub/fn_800BF828.c"),
            Object(Matching, "stub/fn_80070D7C.c"),
            Object(Matching, "stub/fn_80070D64.c"),
            Object(Matching, "stub/fn_8006FE30.c"),
            Object(Matching, "stub/fn_8005F79C.c"),
            Object(Matching, "stub/fn_8005F794.c"),
            Object(Matching, "stub/fn_8005A744.c"),
            Object(Matching, "stub/fn_8004E5C4.c"),
            Object(Matching, "stub/fn_8004E580.c"),
            Object(Matching, "stub/fn_8003CEE4.c"),
            Object(Matching, "stub/fn_80034278.c"),
            Object(Matching, "stub/fn_80033124.c"),
            Object(Matching, "stub/fn_80015DAC.c"),
            Object(Matching, "stub/fn_800121A8.c"),
            Object(Matching, "stub/fn_80010F70.c"),
            Object(Matching, "stub/fn_804064CC.c"),
            Object(Matching, "stub/fn_804035C4.c"),
            Object(Matching, "stub/fn_804035B4.c"),
            Object(Matching, "stub/fn_80402CB8.c"),
            Object(Matching, "stub/fn_80401AA4.c"),
            Object(Matching, "stub/fn_80400D90.c"),
            Object(Matching, "stub/fn_803FC97C.c"),
            Object(Matching, "stub/fn_803EBBD8.c"),
            Object(Matching, "stub/fn_803EB3B4.c"),
            Object(Matching, "stub/fn_803CB000.c"),
            Object(Matching, "stub/fn_803C759C.c"),
            Object(Matching, "stub/fn_803C2E88.c"),
            Object(Matching, "stub/fn_803C27E4.c"),
            Object(Matching, "stub/fn_803A7AF4.c"),
            Object(Matching, "stub/fn_803A49A8.c"),
            Object(Matching, "stub/fn_80397564.c"),
            Object(Matching, "stub/fn_80390948.c"),
            Object(Matching, "stub/fn_8038FD6C.c"),
            Object(Matching, "stub/fn_8037BE78.c"),
            Object(Matching, "stub/fn_8037BE6C.c"),
            Object(Matching, "stub/fn_80362F4C.c"),
            Object(Matching, "stub/fn_8035D770.c"),
            Object(Matching, "stub/fn_8035D720.c"),
            Object(Matching, "stub/fn_8035D254.c"),
            Object(Matching, "stub/fn_80354760.c"),
            Object(Matching, "stub/fn_8034D938.c"),
            Object(Matching, "stub/fn_8034C604.c"),
            Object(Matching, "stub/fn_8034C4DC.c"),
            Object(Matching, "stub/fn_8032D974.c"),
            Object(Matching, "stub/fn_8032C2B0.c"),
            Object(Matching, "stub/fn_8032BD64.c"),
            Object(Matching, "stub/fn_80326A60.c"),
            Object(Matching, "stub/fn_80326998.c"),
            Object(Matching, "stub/fn_80325F84.c"),
            Object(Matching, "stub/fn_80324968.c"),
            Object(Matching, "stub/fn_80323784.c"),
            Object(Matching, "stub/fn_8031577C.c"),
            Object(Matching, "stub/fn_8031351C.c"),
            Object(Matching, "stub/fn_80313080.c"),
            Object(Matching, "stub/fn_80303700.c"),
            Object(Matching, "stub/fn_803028E8.c"),
            Object(Matching, "stub/fn_803010FC.c"),
            Object(Matching, "stub/fn_802FBF70.c"),
            Object(Matching, "stub/fn_802FB45C.c"),
            Object(Matching, "stub/fn_802F3284.c"),
            Object(Matching, "stub/fn_802F2ECC.c"),
            Object(Matching, "stub/fn_802F0AE0.c"),
            Object(Matching, "stub/fn_802F0568.c"),
            Object(Matching, "stub/fn_802EFFD8.c"),
            Object(Matching, "stub/fn_802EFFBC.c"),
            Object(Matching, "stub/fn_802EFFB8.c"),
            Object(Matching, "stub/fn_802EFFA0.c"),
            Object(Matching, "stub/fn_802EA884.c"),
            Object(Matching, "stub/fn_802E96CC.c"),
            Object(Matching, "stub/fn_802E83BC.c"),
            Object(Matching, "stub/fn_802E7B00.c"),
            Object(Matching, "stub/fn_802E58F4.c"),
            Object(Matching, "stub/fn_802E58E8.c"),
            Object(Matching, "stub/fn_802E5820.c"),
            Object(Matching, "stub/fn_802E5758.c"),
            Object(Matching, "stub/fn_802E5370.c"),
            Object(Matching, "stub/fn_802E3950.c"),
            Object(Matching, "stub/fn_802E2228.c"),
            Object(Matching, "stub/fn_802E2218.c"),
            Object(Matching, "stub/fn_802E1E80.c"),
            Object(Matching, "stub/fn_802E0304.c"),
            Object(Matching, "stub/fn_802DE944.c"),
            Object(Matching, "stub/fn_802DE7B4.c"),
            Object(Matching, "stub/fn_802DE238.c"),
            Object(Matching, "stub/fn_802DDAF4.c"),
            Object(Matching, "stub/fn_802DD518.c"),
            Object(Matching, "stub/fn_802DD4F4.c"),
            Object(Matching, "stub/fn_802DB878.c"),
            Object(Matching, "stub/fn_802DB620.c"),
            Object(Matching, "stub/fn_802DB598.c"),
            Object(Matching, "stub/fn_802DAD74.c"),
            Object(Matching, "stub/fn_802DA618.c"),
            Object(Matching, "stub/fn_802D9AD8.c"),
            Object(Matching, "stub/fn_802D9664.c"),
            Object(Matching, "stub/fn_802D95E0.c"),
            Object(Matching, "stub/fn_802D9424.c"),
            Object(Matching, "stub/fn_802D8000.c"),
            Object(Matching, "stub/fn_802D7FCC.c"),
            Object(Matching, "stub/fn_802D7FC0.c"),
            Object(Matching, "stub/fn_802D7704.c"),
            Object(Matching, "stub/fn_802D766C.c"),
            Object(Matching, "stub/fn_802D67FC.c"),
            Object(Matching, "stub/fn_802D65D8.c"),
            Object(Matching, "stub/fn_802D5F20.c"),
            Object(Matching, "stub/fn_802D5E1C.c"),
            Object(Matching, "stub/fn_802D52F4.c"),
            Object(Matching, "stub/fn_802D45C8.c"),
            Object(Matching, "stub/fn_802D2F44.c"),
            Object(Matching, "stub/fn_802D2798.c"),
            Object(Matching, "stub/fn_802D16BC.c"),
            Object(Matching, "stub/fn_802D0BDC.c"),
            Object(Matching, "stub/fn_802D0A24.c"),
            Object(Matching, "stub/fn_802D0084.c"),
            Object(Matching, "stub/fn_802CEE74.c"),
            Object(Matching, "stub/fn_802CEAA8.c"),
            Object(Matching, "stub/fn_802CE81C.c"),
            Object(Matching, "stub/fn_802CD9B0.c"),
            Object(Matching, "stub/fn_802CD510.c"),
            Object(Matching, "stub/fn_802CB640.c"),
            Object(Matching, "stub/fn_802CACFC.c"),
            Object(Matching, "stub/fn_802CACF8.c"),
            Object(Matching, "stub/fn_802C8C38.c"),
            Object(Matching, "stub/fn_802C6430.c"),
            Object(Matching, "stub/fn_802C3E84.c"),
            Object(Matching, "stub/fn_802C0A34.c"),
            Object(Matching, "stub/fn_802C0A28.c"),
            Object(Matching, "stub/fn_802C09F0.c"),
            Object(Matching, "stub/fn_802C05E4.c"),
            Object(Matching, "stub/fn_802C05D4.c"),
            Object(Matching, "stub/fn_802C05B8.c"),
            Object(Matching, "stub/fn_802C05B0.c"),
            Object(Matching, "stub/fn_802C0530.c"),
            Object(Matching, "stub/fn_802BD694.c"),
            Object(Matching, "stub/fn_802BAB20.c"),
            Object(Matching, "stub/fn_802B7A00.c"),
            Object(Matching, "stub/fn_802B7894.c"),
            Object(Matching, "stub/fn_802B1938.c"),
            Object(Matching, "stub/fn_802B0D0C.c"),
            Object(Matching, "stub/fn_802AEDFC.c"),
            Object(Matching, "stub/fn_802AA304.c"),
            Object(Matching, "stub/fn_802AA2C4.c"),
            Object(Matching, "stub/fn_8029B6A0.c"),
            Object(Matching, "stub/fn_80280CAC.c"),
            Object(Matching, "stub/fn_802997CC.c"),
            Object(Matching, "stub/fn_80298EA8.c"),
            Object(Matching, "stub/fn_80297754.c"),
            Object(Matching, "stub/fn_80297494.c"),
            Object(Matching, "stub/fn_80296EEC.c"),
            Object(Matching, "stub/fn_80296734.c"),
            Object(Matching, "stub/fn_80295104.c"),
            Object(Matching, "stub/fn_80294910.c"),
            Object(Matching, "stub/fn_802947F0.c"),
            Object(Matching, "stub/fn_802943DC.c"),
            Object(Matching, "stub/fn_80290AC0.c"),
            Object(Matching, "stub/fn_8028D8BC.c"),
            Object(Matching, "stub/fn_8028D8A0.c"),
            Object(Matching, "stub/fn_8028D898.c"),
            Object(Matching, "stub/fn_8028D5C8.c"),
            Object(Matching, "stub/fn_8028D46C.c"),
            Object(Matching, "stub/fn_8028D184.c"),
            Object(Matching, "stub/fn_8028CFA4.c"),
            Object(Matching, "stub/fn_8028C678.c"),
            Object(Matching, "stub/fn_8028BCC8.c"),
            Object(Matching, "stub/fn_8028B5D8.c"),
            Object(Matching, "stub/fn_8028B328.c"),
            Object(Matching, "stub/fn_8028B0E8.c"),
            Object(Matching, "stub/fn_8028AD20.c"),
            Object(Matching, "stub/fn_8028ABD8.c"),
            Object(Matching, "stub/fn_8028AA08.c"),
            Object(Matching, "stub/fn_8028A914.c"),
            Object(Matching, "stub/fn_8028A860.c"),
            Object(Matching, "stub/fn_8028A7A0.c"),
            Object(Matching, "stub/fn_8028A6F0.c"),
            Object(Matching, "stub/fn_8028A52C.c"),
            Object(Matching, "stub/fn_8028A040.c"),
            Object(Matching, "stub/fn_80289D0C.c"),
            Object(Matching, "stub/fn_80289BFC.c"),
            Object(Matching, "stub/fn_80280CCC.c"),
            Object(Matching, "stub/fn_80280CB4.c"),
            Object(Matching, "stub/fn_8027FAC8.c"),
            Object(Matching, "stub/fn_801C106C.c"),
            Object(Matching, "stub/fn_8027E5A0.c"),
            Object(Matching, "stub/fn_8027E358.c"),
            Object(Matching, "stub/fn_8027C620.c"),
            Object(Matching, "stub/fn_8027C0FC.c"),
            Object(Matching, "stub/fn_8027C0F8.c"),
            Object(Matching, "stub/fn_8027BC90.c"),
            Object(Matching, "stub/fn_8027B5D0.c"),
            Object(Matching, "stub/fn_8027ABA4.c"),
            Object(Matching, "stub/fn_8027A84C.c"),
            Object(Matching, "stub/fn_8027A1CC.c"),
            Object(Matching, "stub/fn_8027A19C.c"),
            Object(Matching, "stub/fn_8027A18C.c"),
            Object(Matching, "stub/fn_802791B0.c"),
            Object(Matching, "stub/fn_80279178.c"),
            Object(Matching, "stub/fn_80279164.c"),
            Object(Matching, "stub/fn_80278AE4.c"),
            Object(Matching, "stub/fn_80278AD8.c"),
            Object(Matching, "stub/fn_8025FCC8.c"),
            Object(Matching, "stub/fn_80254368.c"),
            Object(Matching, "stub/fn_8025226C.c"),
            Object(Matching, "stub/fn_8024AECC.c"),
            Object(Matching, "stub/fn_8023CD18.c"),
            Object(Matching, "stub/fn_8023BDC8.c"),
            Object(Matching, "stub/fn_80234AAC.c"),
            Object(Matching, "stub/fn_80233F84.c"),
            Object(Matching, "stub/fn_80231538.c"),
            Object(Matching, "stub/fn_80230570.c"),
            Object(Matching, "stub/fn_80230500.c"),
            Object(Matching, "stub/fn_8023044C.c"),
            Object(Matching, "stub/fn_8022E920.c"),
            Object(Matching, "stub/fn_80228A80.c"),
            Object(Matching, "stub/fn_80223918.c"),
            Object(Matching, "stub/fn_80222D3C.c"),
            Object(Matching, "stub/fn_80211078.c"),
            Object(Matching, "stub/fn_80210EE4.c"),
            Object(Matching, "stub/fn_8020CAE8.c"),
            Object(Matching, "stub/fn_80204E58.c"),
            Object(Matching, "stub/fn_80201518.c"),
            Object(Matching, "stub/fn_80200D8C.c"),
            Object(Matching, "stub/fn_802009C4.c"),
            Object(Matching, "stub/fn_801FEBB8.c"),
            Object(Matching, "stub/fn_801FEA44.c"),
            Object(Matching, "stub/fn_801FB6C0.c"),
            Object(Matching, "stub/fn_801F6A8C.c"),
            Object(Matching, "stub/fn_801F3B44.c"),
            Object(Matching, "stub/fn_801E2980.c"),
            Object(Matching, "stub/fn_801E047C.c"),
            Object(Matching, "stub/fn_801DD694.c"),
            Object(Matching, "stub/fn_801D4F6C.c"),
            Object(Matching, "stub/fn_801D2ACC.c"),
            Object(Matching, "stub/fn_801CF32C.c"),
            Object(Matching, "stub/fn_801C4268.c"),
            Object(Matching, "stub/fn_801C10E0.c"),
            Object(Matching, "stub/fn_801C1074.c"),
            Object(Matching, "stub/fn_801C0F88.c"),
            Object(Matching, "stub/fn_801B4A38.c"),
            Object(Matching, "stub/fn_801BF094.c"),
            Object(Matching, "stub/fn_801BEF38.c"),
            Object(Matching, "stub/fn_801B4A48.c"),
            Object(Matching, "stub/fn_801B4A3C.c"),
            Object(Matching, "stub/fn_8019C984.c"),
            Object(Matching, "stub/fn_80182B3C.c"),
            Object(Matching, "stub/fn_8019C97C.c"),
            Object(Matching, "stub/fn_8019BBC0.c"),
            Object(Matching, "stub/fn_8019BBA4.c"),
            Object(Matching, "stub/fn_80199D50.c"),
            Object(Matching, "stub/fn_80199D34.c"),
            Object(Matching, "stub/fn_8019939C.c"),
            Object(Matching, "stub/fn_8019938C.c"),
            Object(Matching, "stub/fn_80198A1C.c"),
            Object(Matching, "stub/fn_80197D54.c"),
            Object(Matching, "stub/fn_80197628.c"),
            Object(Matching, "stub/fn_8018BD00.c"),
            Object(Matching, "stub/fn_80187D94.c"),
            Object(Matching, "stub/fn_80183020.c"),
            Object(Matching, "stub/fn_80182AE0.c"),
            Object(Matching, "stub/fn_8017941C.c"),
            Object(Matching, "stub/fn_8017FBFC.c"),
            Object(Matching, "stub/fn_8017F894.c"),
            Object(Matching, "stub/fn_8017BC34.c"),
            Object(Matching, "stub/fn_8016E0C0.c"),
            Object(Matching, "stub/fn_80065454.c"),
            Object(Matching, "stub/fn_8016C47C.c"),
            Object(Matching, "stub/fn_8016B6DC.c"),
            Object(Matching, "stub/fn_8015E0C0.c"),
            Object(Matching, "stub/fn_8015DB08.c"),
            Object(Matching, "stub/fn_8015D700.c"),
            Object(Matching, "stub/fn_8015D330.c"),
            Object(Matching, "stub/fn_8015D308.c"),
            Object(Matching, "stub/fn_8015D300.c"),
            Object(Matching, "stub/fn_8015CC38.c"),
            Object(Matching, "stub/fn_8015CC1C.c"),
            Object(Matching, "stub/fn_8015CBF8.c"),
            Object(Matching, "stub/fn_80159B28.c"),
            Object(Matching, "stub/fn_801593CC.c"),
            Object(Matching, "stub/fn_8014CD5C.c"),
            Object(Matching, "stub/fn_8014C960.c"),
            Object(Matching, "stub/fn_8014C754.c"),
            Object(Matching, "stub/fn_80143C44.c"),
            Object(Matching, "stub/fn_8013D118.c"),
            Object(Matching, "stub/fn_8013D09C.c"),
            Object(Matching, "stub/fn_80132228.c"),
            Object(Matching, "stub/fn_80132224.c"),
            Object(Matching, "stub/fn_8012407C.c"),
            Object(Matching, "stub/fn_80112C90.c"),
            Object(Matching, "stub/fn_80108544.c"),
            Object(Matching, "stub/fn_80106E40.c"),
            Object(Matching, "stub/fn_801056DC.c"),
            Object(Matching, "stub/fn_80103C40.c"),
            Object(Matching, "stub/fn_800FD448.c"),
            Object(Matching, "stub/fn_800F6D0C.c"),
            Object(Matching, "stub/fn_800F59A4.c"),
            Object(Matching, "stub/fn_800F28EC.c"),
            Object(Matching, "stub/fn_800F1010.c"),
            Object(Matching, "stub/fn_800E60E0.c"),
            Object(Matching, "stub/fn_800E3384.c"),
            Object(Matching, "stub/fn_800DA6E8.c"),
            Object(Matching, "stub/fn_800C9B3C.c"),
            Object(Matching, "stub/fn_800C137C.c"),
            Object(Matching, "stub/fn_800C11F0.c"),
            Object(Matching, "stub/fn_800B85AC.c"),
            Object(Matching, "stub/fn_800B08A0.c"),
            Object(Matching, "stub/fn_800B0854.c"),
            Object(Matching, "stub/fn_800B0790.c"),
            Object(Matching, "stub/fn_800A7D5C.c"),
            Object(Matching, "stub/fn_800A6CF4.c"),
            Object(Matching, "stub/fn_800A5F6C.c"),
            Object(Matching, "stub/fn_8009CC20.c"),
            Object(Matching, "stub/fn_8009C618.c"),
            Object(Matching, "stub/fn_8009BA28.c"),
            Object(Matching, "stub/fn_8009A040.c"),
            Object(Matching, "stub/fn_800986A8.c"),
            Object(Matching, "stub/fn_80096690.c"),
            Object(Matching, "stub/fn_80095F70.c"),
            Object(Matching, "stub/fn_80080A64.c"),
            Object(Matching, "stub/fn_8007E3A4.c"),
            Object(Matching, "stub/fn_8007BC98.c"),
            Object(Matching, "stub/fn_8007748C.c"),
            Object(Matching, "stub/fn_8006EBC4.c"),
            Object(Matching, "stub/fn_80065E60.c"),
            Object(Matching, "stub/fn_80065BF8.c"),
            Object(Matching, "stub/fn_8005F660.c"),
            Object(Matching, "stub/fn_8005B830.c"),
            Object(Matching, "stub/fn_8005A9BC.c"),
            Object(Matching, "stub/fn_8005A988.c"),
            Object(Matching, "stub/fn_800569F8.c"),
            Object(Matching, "stub/fn_8004EFA0.c"),
            Object(Matching, "stub/fn_80047FC8.c"),
            Object(Matching, "stub/fn_8004755C.c"),
            Object(Matching, "stub/fn_80046A24.c"),
            Object(Matching, "stub/fn_80036754.c"),
            Object(Matching, "stub/fn_8003626C.c"),
            Object(Matching, "stub/fn_80033B44.c"),
            Object(Matching, "stub/fn_800259A0.c"),
            Object(Matching, "stub/fn_8001B9E8.c"),
            Object(Matching, "stub/fn_80011C70.c"),
            Object(Matching, "stub/fn_80011C2C.c"),
            Object(Matching, "stub/fn_8000E7AC.c"),
            Object(Matching, "stub/fn_8000E1F4.c"),
            Object(Matching, "stub/fn_80132230.c"),
            Object(Matching, "stub/fn_800FB3A4.c"),
            Object(Matching, "stub/fn_800F5EC8.c"),
            Object(Matching, "stub/fn_80011148.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/gdev_cc_shutdown.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/gdev_cc_close.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/uart.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/usr_put.c"),
            Object(Matching, "TRK_MINNOW_DOLPHIN/soh.c"),
        ],
    },
    # The DOL
    {
        "lib": "sora",
        "mw_version": config.linker_version,
        "cflags": cflags_common,
        "host": False,
        "objects": [
            Object(Matching, "sora/sr/sr_getappname.cpp"),
            Object(Matching, "sora/sr/sr_common.cpp"),
            Object(Matching, "sora/sr/sr_revision.cpp"),
            Object(Matching, "sora/main.cpp"),
            Object(Matching, "sora/gf/gf_3d_scene_event.cpp"),
            Object(Matching, "sora/gf/gf_3d_scene_light_resource.cpp"),
            Object(Matching, "sora/gf/gf_archive_load_thread.cpp"),
            Object(Matching, "sora/gf/gf_archive_file.cpp"),
            Object(Matching, "sora/gf/gf_archive_db.cpp"),
            Object(Matching, "sora/gf/gf_camera_controller.cpp"),
            Object(Matching, "sora/gf/gf_callback.cpp"),
            Object(Matching, "sora/gf/gf_decomp.cpp"),
            Object(Matching, "sora/gf/gf_error_check.cpp"),
            Object(Matching, "sora/gf/gf_file_io_handle.cpp"),
            Object(Matching, "sora/gf/gf_file_io_request.cpp"),
            Object(Matching, "sora/gf/gf_gameframe_counter.cpp"),
            Object(Matching, "sora/gf/gf_keep_fb.cpp"),
            Object(Matching, "sora/gf/gf_memory_util.cpp"),
            Object(Matching, "sora/gf/gf_pad_queue.cpp"),
            Object(Matching, "sora/gf/gf_pad_thread.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/gf/gf_task.cpp"),
            Object(NonMatching, "sora/gf/gf_task_scheduler.cpp"),
            Object(Matching, "sora/gf/gf_thread.cpp"),
            Object(Matching, "sora/gf/gf_shutdown_manager.cpp"),
            Object(NonMatching, "sora/gf/gf_slow_manager.cpp"),
            Object(Matching, "sora/gf/gf_system_callback.cpp"),
            Object(Matching, "sora/gf/gf_capture_util.cpp"),
            Object(Matching, "sora/gf/gf_monitor.cpp"),
            Object(Matching, "sora/gf/gf_resource_loader.cpp"),
            Object(NonMatching, "sora/mt/mt_vector_old.cpp"),
            Object(Matching, "sora/mt/mt_prng.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/mt/mt_prng_log.cpp"),
            Object(Matching, "sora/st/module.cpp"),
            Object(Matching, "sora/ut/ut_nw.cpp"),
            Object(NonMatching, "sora/ut/ut_relocate.cpp"),
            Object(Matching, "sora/ut/ut_list.cpp"),
            Object(Matching, "sora/ip/ip_human.cpp"),
            Object(NonMatching, "sora/ip/ip_network_producer.cpp"),
            Object(Matching, "sora/ef/ef_screen_handle.cpp"),
            Object(Matching, "sora/ec/ec_trace_mgr.cpp"),
            Object(Matching, "sora/snd/snd_init_thread.cpp"),
            Object(Matching, "sora/mv/mv_THPAudioDecode.cpp"),
            Object(Matching, "sora/mv/mv_THPRead.cpp"),
            Object(Matching, "sora/cm/cm_controller_default.cpp", extra_cflags=["-RTTI off"]),
            Object(NonMatching, "sora/cm/cm_controller_menu_fixed.cpp"),
            Object(Matching, "sora/cm/cm_controller_melee_fixed.cpp"),
            Object(Matching, "sora/cm/cm_stage_param.cpp"),
            Object(NonMatching, "sora/ty/ty_fig_listmng.cpp"),
            Object(Matching, "sora/if/if_wifipr_task.cpp"),
            Object(Matching, "sora/if/if_adv_task.cpp"),
            Object(Matching, "sora/if/if_stgedit.cpp"),
            Object(Matching, "sora/gr/collision/gr_collision_shape.cpp"),
            Object(Matching, "sora/gr/collision/gr_collision_data.cpp"),
            Object(Matching, "sora/gr/collision/gr_collision_handle.cpp"),
            Object(Matching, "sora/gr/collision/gr_collision_shape_rhombus.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/gr/collision/gr_collision_shape_circle.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/gr/gr_path.cpp"),
            Object(NonMatching, "sora/ac/ac_cmd_interpreter.cpp"),
            Object(Matching, "sora/ac/ac_anim_cmd_impl.cpp"),
            Object(Matching, "sora/ac/ac_null.cpp"),
            Object(Matching, "sora/ft/ft_system.cpp"),
            Object(Matching, "sora/nt/nt_offline.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/nt/d_net_connect.cpp"),
            Object(Matching, "sora/nt/nt_etc_dwc.cpp", extra_cflags=["-RTTI off"]),
            Object(Matching, "sora/ad/ad_static_data.cpp"),
            Object(Matching, "sora/st/st_data_container.cpp"),
        ],
    },
    # Common REL units
    {
        "lib": "REL",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_adv_menu/mo_adv_menu.cpp"),
            Object(Matching, "mo_fighter/mo_fighter.cpp"),
            Object(Matching, "mo_menu/mo_menu.cpp"),
            Object(Matching, "mo_stage/mo_stage.cpp"),
            Object(Matching, "global_destructor_chain.c"),
            Object(Matching, "home_button_icon.cpp"),
        ],
    },
    # The RELs
    {
        "lib": "ft_captain",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_dedede",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_diddy",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_donkey",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_falco",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_fox",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_gamewatch",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_ganon",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_iceclimber",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_ike",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_kirby",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_koopa",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_link",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_lucario",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_lucas",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_luigi",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_mario",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_marth",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(NonMatching, "mo_fighter/ft_marth/ft_marth.cpp"),
            Object(NonMatching, "mo_fighter/ft_marth/ft_marth_status_uniq_process_special_s.cpp"),
            Object(NonMatching, "mo_fighter/ft_marth/ft_marth_status_uniq_process_special_hi.cpp"),
            Object(NonMatching, "mo_fighter/ft_marth/ft_marth_status_uniq_process_special_lw.cpp"),
            Object(NonMatching, "mo_fighter/ft_marth/ft_marth_status_uniq_process_special_final.cpp"),
            Object(NonMatching, "mo_fighter/ft_marth/if_marth_final.cpp"),
            Object(Matching, "mo_stub/ft_dedede/fn_117_A2B4.c"),
            Object(Matching, "mo_stub/ft_dedede/fn_117_A300.c"),
            Object(Matching, "mo_stub/ft_dedede/fn_117_A394.c"),
            Object(Matching, "mo_stub/ft_dedede/fn_117_A3C0.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_6C60.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_948C.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_94D4.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_9568.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_9594.c"),
            Object(Matching, "mo_stub/ft_captain/fn_100_95A4.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_6E9C.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_95F8.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_9640.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_96D4.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_9700.c"),
            Object(Matching, "mo_stub/ft_donkey/fn_92_9710.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_8008.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_AD90.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_ADD8.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_AE6C.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_AE98.c"),
            Object(Matching, "mo_stub/ft_falco/fn_108_AEA8.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_8138.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_AEEC.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_AF34.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_AFC8.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_AFF4.c"),
            Object(Matching, "mo_stub/ft_fox/fn_97_B004.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_8720.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C140.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C18C.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C190.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C220.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C24C.c"),
            Object(Matching, "mo_stub/ft_gamewatch/fn_107_C258.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_6868.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_8DF4.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_8E3C.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_8ED0.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_8EFC.c"),
            Object(Matching, "mo_stub/ft_ganon/fn_109_8F0C.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_58E4.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_956C.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_95AC.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_9640.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_966C.c"),
            Object(Matching, "mo_stub/ft_ike/fn_119_9680.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_61A8.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8D74.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8DC0.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8DC4.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8E54.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8E80.c"),
            Object(Matching, "mo_stub/ft_koopa/fn_102_8E8C.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_8BC0.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_C9CC.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_CA18.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_CA1C.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_CAAC.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_CAD8.c"),
            Object(Matching, "mo_stub/ft_lucas/fn_114_CAE4.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_6178.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_8690.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_86D8.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_876C.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_8798.c"),
            Object(Matching, "mo_stub/ft_luigi/fn_99_87A8.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_22B4.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_A394.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_A3D8.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_A46C.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_A498.c"),
            Object(Matching, "mo_stub/ft_mario/fn_91_A4A8.c"),
        ],
    },
    {
        "lib": "ft_metaknight",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_ness",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_peach",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_pikachu",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_pikmin",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_pit",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_poke",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_purin",
        "mw_version": config.linker_version,
        "cflags": cflags_fighter,
        "host": False,
        "objects": [
            Object(NonMatching, "mo_fighter/ft_purin/ft_purin.cpp"),
            Object(Matching, "mo_stub/ft_ness/fn_101_92E8.c"),
            Object(Matching, "mo_stub/ft_ness/fn_101_CF94.c"),
            Object(Matching, "mo_stub/ft_ness/fn_101_CFDC.c"),
            Object(Matching, "mo_stub/ft_ness/fn_101_D070.c"),
            Object(Matching, "mo_stub/ft_ness/fn_101_D09C.c"),
            Object(Matching, "mo_stub/ft_ness/fn_101_D0AC.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_72A4.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9D4C.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9D98.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9D9C.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9E2C.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9E58.c"),
            Object(Matching, "mo_stub/ft_peach/fn_103_9E64.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_744C.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_9C28.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_9C70.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_9D04.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_9D30.c"),
            Object(Matching, "mo_stub/ft_pikachu/fn_98_9D40.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_686C.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_7FA8.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_7FBC.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_8094.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_80A4.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_80D8.c"),
            Object(Matching, "mo_stub/ft_pikmin/fn_113_80F4.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_774C.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_A5C4.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_A60C.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_A6A0.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_A6CC.c"),
            Object(Matching, "mo_stub/ft_pit/fn_112_A6DC.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_B464.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_B85C.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_B964.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_B978.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_B990.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_BAB0.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_BBB4.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_BC50.c"),
            Object(Matching, "mo_stub/ft_purin/fn_124_BC54.c"),
        ],
    },
    {
        "lib": "ft_robot",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_samus",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_snake",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_sonic",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_toonlink",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_wario",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_wolf",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_yoshi",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_zako",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "ft_zelda",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_difficulty",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_ending",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_game_over",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_name",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_result",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_save_load",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_save_point",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_seal",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_sel_char",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_sel_map",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_telop",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_menu_visual",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_adv_stage",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_adv_stage/gr_adventure_final.cpp"),
            Object(Matching, "mo_adv_stage/mo_adv_stage.cpp"),
            Object(Matching, "mo_stub/ft_samus/fn_94_6CF8.c"),
            Object(Matching, "mo_stub/ft_samus/fn_94_A8D0.c"),
            Object(Matching, "mo_stub/ft_samus/fn_94_A918.c"),
            Object(Matching, "mo_stub/ft_samus/fn_94_A9AC.c"),
            Object(Matching, "mo_stub/ft_samus/fn_94_A9D8.c"),
            Object(Matching, "mo_stub/ft_samus/fn_94_A9E8.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_6E04.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_9468.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_94B0.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_9544.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_9570.c"),
            Object(Matching, "mo_stub/ft_wario/fn_110_9580.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_8060.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_AE04.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_AE4C.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_AEE0.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_AF0C.c"),
            Object(Matching, "mo_stub/ft_wolf/fn_125_AF1C.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_8008.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_B428.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_B470.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_B504.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_B530.c"),
            Object(Matching, "mo_stub/ft_yoshi/fn_95_B540.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_51C8.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_70CC.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_7118.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_711C.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_71AC.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_71D8.c"),
            Object(Matching, "mo_stub/ft_zako/fn_126_71E4.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_7930.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A5CC.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A618.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A61C.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A6AC.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A6D8.c"),
            Object(Matching, "mo_stub/ft_zelda/fn_104_A6E4.c"),
            Object(Matching, "mo_stub/sora_adv_menu_difficulty/fn_32_7EC.c"),
            Object(Matching, "mo_stub/sora_adv_menu_difficulty/fn_32_B34.c"),
            Object(Matching, "mo_stub/sora_adv_menu_game_over/fn_33_2CC0.c"),
            Object(Matching, "mo_stub/sora_adv_menu_game_over/fn_33_34B8.c"),
            Object(Matching, "mo_stub/sora_adv_menu_name/fn_28_1920.c"),
            Object(Matching, "mo_stub/sora_adv_menu_name/fn_28_2888.c"),
            Object(Matching, "mo_stub/sora_adv_menu_result/fn_34_C0C.c"),
            Object(Matching, "mo_stub/sora_adv_menu_sel_map/fn_31_2928.c"),
            Object(Matching, "mo_stub/sora_adv_menu_sel_map/fn_31_2BD4.c"),
            Object(Matching, "mo_stub/sora_adv_menu_sel_map/fn_31_2D94.c"),
            Object(Matching, "mo_stub/sora_adv_menu_visual/fn_29_2BA0.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_44C.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_45C.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_38B8.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_4408.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_4798.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_5098.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_8A88.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_8A94.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_8ADC.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_8AEC.c"),
            Object(Matching, "mo_stub/sora_adv_stage/fn_40_8B10.c"),
        ],
    },
    {
        "lib": "sora_enemy",
        "mw_version": config.linker_version,
        "cflags": cflags_sora_enemy,
        "host": False,
        "objects": [
            Object(Matching, "mo_enemy/sora_enemy/em_info.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/em_create.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/resource/em_resource_module_impl.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/stop/em_stop_module_impl.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/em_extend_param_accesser.cpp"),
            Object(NonMatching, "mo_enemy/sora_enemy/em_external_value_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/em_target_search_unit.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/wnem/wn_em_resource_module_impl.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/wnem/wn_em_heap_module_impl.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/boobas/em_boobas_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/siralamos/em_siralamos_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/roada/em_roada_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/killer/em_killer_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/popperam/em_popperam_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/pacci/em_pacci_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/jyakeel/em_jyakeel_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/aroaros/em_aroaros_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/cymal/em_cymal_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/deathpod/em_deathpod_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/dekakuribo/em_dekakuribo_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/bucyulus/em_bucyulus_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/botron/em_botron_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/gyraan/em_gyraan_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/mite/em_mite_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/prim/em_prim_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/cataguard/em_cataguard_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/wnem/wn_em_report.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/kuribo/em_kuribo_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/flows/em_flows_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/tautau/em_tautau_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/shelly/em_shelly_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/teckin/em_teckin_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/spar/em_spar_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/hammerbros/em_hammerbros_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/kokkon/em_kokkon_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/bombhead/em_bombhead_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/ngagog/em_ngagog_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/faulong/em_faulong_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/bitan/em_bitan_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/patapata/em_patapata_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/jdus/em_jdus_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/ghamgha/em_ghamgha_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/robobeam/em_robobeam_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/robodistance/em_robodistance_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/robohoming/em_robohoming_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/robopunch/em_robopunch_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/arman/em_arman_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/arman/wnem_proc_arman.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/galfire/em_galfire_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/bosspackun/em_bosspackun_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/ghamghabase/em_ghamghabase_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/galleom/em_galleom_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/ridley/em_ridley_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/rayquaza/em_rayquaza_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/rayquaza/wnem_proc_rayquaza.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/duon/em_duon_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/porky/em_porky_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/metaridley/em_metaridley_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/falconflyer/em_falconflyer_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/taboo/em_taboo_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/taboo/wnem_proc_taboo.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/masterhand/em_masterhand_param_accesser.cpp"),
            Object(Matching, "mo_enemy/sora_enemy/crazyhand/em_crazyhand_param_accesser.cpp"),
            Object(Matching, "mo_enemy/mo_enemy.cpp"),
        ],
    },
    {
        "lib": "sora_melee",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_melee/sora_melee/so/model/so_model_module_simple.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/model/so_model_virtual_node.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/model/so_model_module_impl_variable.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/anim/so_anim_chr.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_controller_module_link_ref.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_heap_module_impl.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_module_accesser.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_resource_module_impl.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_general_work.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_general_work_abstract.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_general_work_simple.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/anim/so_anim_cmd_interpreter_effect.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_photo_call_back.cpp"),
            Object(Matching, "mo_melee/sora_melee/so/so_common_data_accesser.cpp"),
            Object(Matching, "mo_melee/sora_melee/ft/ft_class_info.cpp"),
            Object(Matching, "mo_melee/sora_melee/ft/ft_extend_param_accesser.cpp"),
            Object(Matching, "mo_melee/sora_melee/ft/ft_fighter_build_data.cpp"),
            Object(Matching, "mo_melee/sora_melee/st/st_common_gimmick.cpp"),
            Object(Matching, "mo_melee/mo_melee.cpp"),
            Object(Matching, "mo_stub/sora_melee/fn_27_E54.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_3624.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_53B8.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_5538.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_60C8.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_60CC.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_6650.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_6BF4.c"),
            Object(Matching, "mo_stub/sora_melee/fn_27_6C00.c"),
        ],
    },
    {
        "lib": "sora_menu_boot",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_challenger",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_collect_viewer",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_edit",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_event",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_fig_get_demo",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_friend_list",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_game_over",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_intro",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_main",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_name",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_qm",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_replay",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_rule",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_sel_char",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_sel_char_access",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_sel_stage",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_simple_ending",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_snap_shot",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_time_result",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_title",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_title_sunset",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_tour",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_menu_watch",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_minigame",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "sora_scene",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_scene/sora_scene/sc_demo.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_tutorial.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_staffroll.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_seal_list.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_seal_disp.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_net_time_result.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_adv_selchar.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_adv_saveload.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_adv_diff.cpp"),
            Object(Matching, "mo_scene/sora_scene/sc_adv_result.cpp"),
            Object(NonMatching, "mo_scene/sora_scene/sc_adv_gameover.cpp"),
            Object(Matching, "mo_scene/mo_scene.cpp"),
            Object(Matching, "mo_scene/sora_scene/stub_fn_1_670.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_40D8.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_618C.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_6624.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_6A24.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_6CB4.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_28D8.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_2EB4.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_59F8.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_59FC.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_5A10.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_6064.c"),
            Object(Matching, "mo_stub/sora_menu_collect_viewer/fn_6_8174.c"),
            Object(Matching, "mo_stub/sora_menu_edit/fn_5_12060.c"),
            Object(Matching, "mo_stub/sora_menu_edit/fn_5_14B7C.c"),
            Object(Matching, "mo_stub/sora_menu_edit/fn_5_14B90.c"),
            Object(Matching, "mo_stub/sora_menu_fig_get_demo/fn_26_B38.c"),
            Object(Matching, "mo_stub/sora_menu_fig_get_demo/fn_26_12A0.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_39B4.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_4698.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_75D4.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_8954.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_902C.c"),
            Object(Matching, "mo_stub/sora_menu_friend_list/fn_14_9594.c"),
            Object(Matching, "mo_stub/sora_menu_game_over/fn_12_1180.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_4160.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_12F48.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_12FD0.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_17DD8.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_1EF58.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_1EF68.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_1EF90.c"),
            Object(Matching, "mo_stub/sora_menu_main/fn_2_2650C.c"),
            Object(Matching, "mo_stub/sora_menu_name/fn_16_49E8.c"),
            Object(Matching, "mo_stub/sora_menu_replay/fn_7_1474.c"),
            Object(Matching, "mo_stub/sora_menu_replay/fn_7_148C.c"),
            Object(Matching, "mo_stub/sora_menu_replay/fn_7_14A0.c"),
            Object(Matching, "mo_stub/sora_menu_replay/fn_7_14E4.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_B30.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_B4C.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_F6C.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_1194.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_1198.c"),
            Object(Matching, "mo_stub/sora_menu_rule/fn_18_12D8.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_1BA4.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_24C0.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_24D8.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_24E0.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_35A0.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_5360.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_5FEC.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char/fn_10_8358.c"),
            Object(Matching, "mo_stub/sora_menu_sel_char_access/fn_17_0.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_3BC.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_958.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_96C.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_980.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_A68.c"),
            Object(Matching, "mo_stub/sora_menu_snap_shot/fn_8_A6C.c"),
            Object(Matching, "mo_stub/sora_menu_title_sunset/fn_25_1424.c"),
            Object(Matching, "mo_stub/sora_menu_title_sunset/fn_25_2FF4.c"),
            Object(Matching, "mo_stub/sora_menu_watch/fn_15_4E7C.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_928.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_256C.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_2CE8.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_2E58.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_2EC4.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_2ED8.c"),
            Object(Matching, "mo_stub/sora_minigame/fn_20_6DB8.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_7F9C.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8148.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8A80.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8A94.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8AB4.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8ACC.c"),
            Object(Matching, "mo_stub/sora_scene/fn_1_8D44.c"),
        ],
    },
    {
        "lib": "st_battle",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_battles",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_config",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_config/st_config.cpp"),
            Object(Matching, "mo_stage/st_config/gr_config.cpp"),
			],
    },
    {
        "lib": "st_crayon",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_crayon/st_crayon.cpp"),
            Object(Matching, "mo_stage/st_crayon/gr_crayon_yakumono.cpp"),
            Object(Matching, "mo_stub/st_battle/fn_43_1E4.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_8C0.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_8E0.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_8F4.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_938.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_950.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_980.c"),
            Object(Matching, "mo_stub/st_battle/fn_43_990.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_138.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_2D8.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_3C4.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_3D8.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_404.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_448.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_470.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_490.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_4A0.c"),
            Object(Matching, "mo_stub/st_battles/fn_42_4BC.c"),
            Object(Matching, "mo_stub/st_crayon/fn_56_500C.c"),
            Object(Matching, "mo_stub/st_crayon/fn_56_512C.c"),
            Object(Matching, "mo_stub/st_crayon/fn_56_536C.c"),
            Object(Matching, "mo_stub/st_crayon/fn_56_5394.c"),
            Object(Matching, "mo_stub/st_crayon/fn_56_53D8.c"),
        ],
    },
    {
        "lib": "st_croll",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dolpic",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_donkey",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxbigblue",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_dxbigblue/gr_dxbigblue.cpp"),
        ],
    },
    {
        "lib": "st_dxcorneria",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxgarden",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxgreens",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxonett",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxpstadium",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxrcruise",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxshrine",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
			Object(Matching, "mo_stage/st_dxshrine/st_dxshrine.cpp"),
			Object(Matching, "mo_stage/st_dxshrine/gr_dxshrine.cpp"),
			],
    },
    {
        "lib": "st_dxyorster",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_dxzebes",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_earth",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_emblem",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
			Object(NonMatching, "mo_stage/st_emblem/st_emblem.cpp"),
            ],
    },
    {
        "lib": "st_famicom",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_final",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_final/st_final.cpp"),
            Object(Matching, "mo_stage/st_final/gr_final.cpp"),
			],
    },
    {
        "lib": "st_fzero",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_greenhill",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_gw",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_halberd",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_heal",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_homerun",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_ice",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_jungle",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_kart",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_madein",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_mansion",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_mariopast",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_metalgear",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_newpork",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_norfair",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_oldin",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_orpheon",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_otrain",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_otrain/st_onlinetrainning.cpp"),
        ],
    },
    {
        "lib": "st_palutena",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_pictchat",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_pirates",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_plankton",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_stadium",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_stageedit",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_starfox",
        "mw_version": config.linker_version,
        "cflags": cflags_st_starfox,
        "host": False,
        "objects": [
            Object(Matching, "mo_stage/st_starfox/st_starfox.cpp"),
        ],
    },
    {
        "lib": "st_tbreak",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_tengan",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
    {
        "lib": "st_village",
        "mw_version": config.linker_version,
        "cflags": cflags_rel,
        "host": False,
        "objects": [],
    },
]

# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    # ProgressCategory("game", "Game Code"),
    # ProgressCategory("sdk", "SDK Code"),
]
config.progress_each_module = args.verbose

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress and write progress.json
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
